### Software paramaters

gene_table: gene_table.tsv
params:
    general:
        num_threads: 4
        maxgap_pct: 0.95
    concatenate:
        min_aln_len: 0
    detect_outliers:
        taxa_threshold: 0.7
        long_branch_threshold: 0.08
        treeshrink_mode: "auto"
